### ISSUE TITLE
extreme slowness in Tor Browser, or user error?

### ISSUE THREAD

**Issue by MikeBosw** [openpgpjs/openpgpjs#875] opened 2019-03-20 02:09 UTC
I've written a [demo](https://mikebosw.github.io/openpgpjs-perf-demo/index.html) to illustrate the issue.

There seems to be a **10x** performance difference between the two browsers when decrypting.

**In Chrome**
Decrypting a single message takes 200 ms the first time and about 30 ms subsequently.
Decrypting > 150 messages takes about 3 seconds.

**In the Tor Browser**
Decrypting a single message takes 2000 ms the first time and about 1200 ms subsequently.
Decrypting > 150 messages takes minutes.

Is everybody else seeing this discrepancy, or am I somehow misusing openpgpjs?

Here's the [source](https://github.com/MikeBosw/openpgpjs-perf-demo/blob/master/src/App.js#L261) of the demo. The computer I'm testing with is a MacBook Pro.

**Comment by twiss** [comment] 2019-03-20 15:02
Hi @MikeBosw! Your code looks fine. I can reproduce the issue only if I set the "Security Slider" to "Safer". The [manual mentions](https://tb-manual.torproject.org/security-slider.html) that at this level "all JavaScript performance optimizations are disabled". This is probably the cause of the issue. At the "Standard" security level, performance is similar to Firefox.

If interoperability with the PGP ecosystem is not important to you, what you could try is to enable AEAD, particularly GCM mode (search the README for instructions). You'll have to re-encrypt the messages, but then decryption can make use of the Web Crypto API, which is implemented natively in the browser. That should hopefully fix part of the performance issue.

**Comment by MikeBosw** [comment] 2019-03-20 16:04
Wow, I appreciate the prompt reply. And it's great to have a lead. Hope restored.

Regarding the slider: my product, [Phitbone](https://phitbone.com), offers browser-side decryption partly because the intended users are precisely the sort of people who actually would care about Tor's safety (read: anonymity) level being set to the max. I imagine the same could be said for a lot of the kinds of products that might make use of browser-side decryption. "Safest" also happens to be the default setting, it seems.

But... interoperability with the PGP ecosystem is indeed unimportant to me. Hence the hope restored :) I'll try that out and update this issue once I've got the new results.

**Comment by twiss** [comment] 2019-03-20 17:53
Np ^.^ I essentially agree with what you wrote, however:

> "Safest" also happens to be the default setting, it seems.

I don't think this is the case - I just installed it and it was on Standard for me, and couldn't reproduce your issue at first. [This FAQ entry](https://www.torproject.org/docs/faq.html.en#TBBJavaScriptEnabled) also claims that and explains why JavaScript is enabled by default, which would contradict "Safest" being the default level.

> But perhaps this performance issue comes down to a genuinely intractable technical barrier?

I believe so - it appears that "all JavaScript performance optimizations are disabled" refers to the entire JIT being disabled. See https://trac.torproject.org/projects/tor/ticket/21011 for some of the perceived risks of the JIT. Encryption at the lowest level is essentially executing the same set of instructions over and over again on a sequential block of data - the sort of thing that a compiler/JIT is good at optimizing.

**Comment by twiss** [comment] 2019-04-29 10:40
Let me know if you've found something interesting! Closing this issue for now as I believe there's nothing actionable for us to do.

**Closed by twiss** 2019-04-29 10:40 UTC
