### ISSUE TITLE
encrypt & sign version 2.3

### ISSUE THREAD

**Issue by rushglen** [openpgpjs/openpgpjs#463] opened 2016-05-26 19:01 UTC
I can encrypt, decrypt, and sign a plaintext message.
I can also in 2 separate operations sign then encrypt a message.

However I'm thinking I should be able to combine signing and encrypting as shown in
https://github.com/openpgpjs/openpgpjs/blob/master/test/general/openpgp.js
line 643 it('should encrypt/sign and decrypt/verify'

The difference from just encrypting is the private key (for signing) is passed in.
I am passing in the private key (decrypted with pass phrase)
 var encOpt = {
            data: plaintext,
            publicKeys: publicKey.keys,
            privateKeys: privateKey.keys
  };
and signing does not occur - their is no error, message is encrypted normally just not signed....

**Comment by neoatlantis** [comment] 2016-05-26 21:53
Yes, and so I have to explicitly call `sign` and then `encrypt` for messages being signed & encrypted: https://bitbucket.org/neoatlantis/brgp/src/5a5fe4f010974067e29f9b8df6472ecfc6f2f169/src/service.compose.js

Also signing works in a blocking way, whereas encrypting returns a Promise. Decrypting is here similar.

**Comment by tanx** [comment] 2016-05-27 06:25
Hey. I just debugged the test and signing works just fine when passing in `privateKeys`. You were referring to this example:
https://github.com/openpgpjs/openpgpjs/blob/master/test/general/openpgp.js#L643-L662

So I can't reconstruct the behavior. Closing this until we can confirm the issue is not in your code.

**Closed by tanx** 2016-05-27 06:25 UTC

**Comment by rushglen** [comment] 2016-05-27 17:41
hmm... not sure why it doesn't work for me. However that's OK as I want to keep the encryption and signing separate for the user so there's a choice of encrypt then sign or sign then encrypt (and I have that working) - I know there's a huge debate about "signing then encrypting" or "encrypting then signing" but I want the user to have the choice.

**Comment by neoatlantis** [comment] 2016-05-27 18:57
@rushglen to encrypt, you should make sure `encOpt.publicKeys` is an array of public keys. `encOpt.privateKeys`  can be either an array of private key instances(decrypted) or one single instance.

To decrypt, the `openpgp.decrypt` supports only one private key supplied.

Notice that if you've used `openpgp.key.readArmored` to load a key, it returns an object, the keys are in its `.keys` attribute.

**Comment by rushglen** [comment] 2016-05-28 20:05
Sorry Tanx, I now see it is working, I wasn't expecting there to be no header/footers (BEGIN PGP SIGNED MESSAGE) etc. so yes your test works.
