### ISSUE TITLE
PrivateKeyObj.decrypt throw : concatUint8Array: Data must be in the form of a Uint8Array

### ISSUE THREAD

**Issue by nicolasmsg** [openpgpjs/openpgpjs#821] opened 2018-12-21 09:36 UTC
Hello I have some trouble trying to use your library.

```
    export const decryptFunc = async(file) => {
        const privateKey = (await openpgp.key.readArmored(privKey)).keys[0]
        await privateKey.decrypt(passphrase)
    }
```

this code sample raise an error : Error: concatUint8Array: Data must be in the form of a Uint8Array.
I don't understand because the doc says passphrases must be  : String | Array.<String>	(https://openpgpjs.org/openpgpjs/doc/module-key.Key.html)
The privateKey Key object looks like that: 

```
    { privateKey:
        Key {
          keyPacket:
          SecretKey {
            tag: 5,
            version: 4,
            created: 2018-12-20T10:04:58.000Z,
            algorithm: 'rsa_encrypt_sign',
            params: [Array],
            expirationTimeV3: 0,
            fingerprint: [Object],
            keyid: [Object],
            encrypted: [Object],
            isEncrypted: true,
            packets: [Object],
            fromStream: false },
          revocationSignatures: [],
          directSignatures: [],
          users: [ [Object] ],
          subKeys: [ [Object] ] 
      } 
    }
```
More interesting, if I remove the await in await privateKey.decrypt(passphrase), it works ! But the key object remains the same (I don't know if it should or not).

From this I tried to continue with this: 

```
    const pubKey = `-----BEGIN PGP PUBLIC KEY BLOCK-----
    ...
    -----END PGP PUBLIC KEY BLOCK-----`

    const privKey = `-----BEGIN PGP PRIVATE KEY BLOCK-----
    ....
    -----END PGP PRIVATE KEY BLOCK-----`

    const encryptedText = `-----BEGIN PGP MESSAGE-----
    ...
    -----END PGP MESSAGE-----
    `

    const passphrase = 'passphrase'


    export const decryptFunc = async() => {
      const privateKey = (await openpgp.key.readArmored(privKey)).keys[0]
      privateKey.decrypt([passphrase])

      const options = {
        message: await openpgp.message.fromText(encryptedText),
        publicKeys: (await openpgp.key.readArmored(pubKey)).keys,
        privateKeys: [privateKey],
        // sessionKeys: { data:encryptedText, algorithm:'rsa_encrypt_sign' }
      }

      return openpgp.decrypt(options).then(plaintext => {
          return plaintext.data
      })
    }
```

This code raise the following error: Error decrypting message: Session key decryption failed.
If i uncommend the sessionKeys line, it returns the undecrypted message.

What im I doing wrong ?

The message has been generated with GPG Keychain, the key is a RSA 4096.
My final goal is to use this library to decrypt and check the signature of some zipfiles in a react-native application.

Thank you.

**Comment by twiss** [comment] 2018-12-21 15:44
Hey! That's rather weird. The original code (with the `await`) looks correct to me.

Could you post a full stack trace of the error? (Perhaps setting `openpgp.config.debug = true` before your code reveals a more informative stack trace.)

**Comment by nicolasmsg** [comment] 2018-12-21 15:56
Here is the complete stack trace : 

`
{ error: Error: concatUint8Array: Data must be in the form of a Uint8Array
        at concatUint8Array (/Users/.../node_modules/openpgp/dist/openpgp.js:23338:13)
        at concat (/Users/.../node_modules/openpgp/dist/openpgp.js:22889:37)
        at Object.transform (/Users/.../node_modules/openpgp/dist/openpgp.js:23036:62)
        at Object.encode_utf8 (/Users/.../node_modules/openpgp/dist/openpgp.js:40499:37)
        at S2K.produce_key (/Users/.../node_modules/openpgp/dist/openpgp.js:40081:31)
        at produceEncryptionKey (/Users/.../node_modules/openpgp/dist/openpgp.js:37159:14)
        at SecretKey.decrypt (/Users/.../node_modules/openpgp/dist/openpgp.js:37207:17)
        at /Users/.../node_modules/openpgp/dist/openpgp.js:31409:29
        at Array.map (<anonymous>)
        at /Users/.../node_modules/openpgp/dist/openpgp.js:31407:35 }
`

**Comment by twiss** [comment] 2018-12-22 04:42
What version of node are you using? This sounds like a bug in its `TextEncoder`, perhaps (which we use internally to convert from String to Uint8Array).

Also, if you feel like debugging, could you see what the calls to `encoder.encode` on `dist/openpgp.js:40497` return?

**Comment by bjd145** [comment] 2019-01-25 16:53
I figured out my issue. I was reading in the file incorrectly using fs.readFileSync .

Changed var fileToDecrypt = fs.readFileSync('./files/sample.txt.enc', 'utf8');  
to var fileToDecrypt = fs.readFileSync('./files/sample.txt.enc');  solved my issue.

**Comment by amity0** [comment] 2019-02-07 09:22
I'm having the same issue with encrypt with compression.zip with node v8.11.3 and openpgp 4.4.3 
I tried to rollback to version 4.4.2 and the issue doesn't reproduce. So I guess something changed in 4.4.3 that causes this issue.

I tried to use @twiss suggestion to install text-encoding-utf-8 but it doesn't seem to make a difference. the eception occurs in openpgp.js/23345 - `concatUint8Array` and the problematic element in my case is:
```
_disturbed:false
_readableStreamController:e {_controlledReadableStream: e, _queue: Array(0), _queueTotalSize: 0, …}
_reader:undefined
_state:"readable"
_storedError:undefined
locked:false
```
that comes from `const data = this.packets.write();` under `SymmetricallyEncrypted.prototype.encrypt` (line 38745)


I rollback to version 4.4.2 for now

**Comment by twiss** [comment] 2019-02-07 15:15
@amity0 thanks, that makes sense. Could you also try
```js
SymmetricallyEncrypted.prototype.encrypt = async function (algo, key) {
  const data = this.packets.write();

  const prefix = await _crypto2.default.getPrefixRandom(algo);
  const FRE = await _crypto2.default.cfb.encrypt(algo, key, prefix, new Uint8Array(_crypto2.default.cipher[algo].blockSize));
  const ciphertext = await _crypto2.default.cfb.encrypt(algo, key, data, FRE.subarray(2));
  this.encrypted = _util2.default.concat([FRE, ciphertext]);

  return true;
};
```
(i.e. in the original version replace `concatUint8Array` with `concat`) and see if that works as well?

Also, the only way you could ever reach this code is if you set `openpgp.config.integrity_protect = false` I think. That's a really bad idea and probably insecure. The documentation probably doesn't state this clearly enough but you should really only be using that if you know what you're doing and signing the data, verifying the signatures before doing anything with the data, etc.

**Comment by amity0** [comment] 2019-02-09 14:02
@twiss Thanks for the reply. You are right (in both cases) we use `integrity_protect = false` and your code line change solves the issue. I would have to ask my team why they decide to use `integrity_protect = false`

Thanks again

**Comment by twiss** [comment] 2019-02-12 11:10
@amity0 your issue should be fixed in the next release by https://github.com/openpgpjs/openpgpjs/commit/40360b4955de7f9ca03ed107d6a3c95c9f087af0.

Please do ask them, it would be useful to know what users of this library need that config option for. My personal preference would be not to have this config option at all since it's insecure, but maybe if there's a legitimate reason we need to keep it.

Just as a guess, if you're also decrypting these messages with OpenPGP.js, you're probably setting `openpgp.config.ignore_mdc_error = true` as well? Otherwise the library doesn't even accept these messages. See #651 for some discussion about the use and future of that option.

**Closed by twiss** 2019-02-12 11:10 UTC

**Comment by amity0** [comment] 2019-02-15 18:30
@twiss I think that it was copied from a gist found somewhere out there. We removed it and everything works fine. Thanks for the information and the help

**Comment by ssancheza227** [comment] 2019-07-09 19:50
Hi @nicolasmsg i'm using https://github.com/jerson/react-native-fast-openpgp is very fast :)

**Comment by jczaplew** [comment] 2022-01-07 17:11
For future Googlers encountering the error `Error: concatUint8Array: Data must be in the form of a Uint8Array` - I was receiving this while passing a binary stream to `encrypt`. When the read stream was created, I was specifying the encoding as `binary` (`fs.createReadStream(__dirname + '/test.pdf', 'binary')`) and receiving this error. When I removed the explicit encoding the error disappear and it worked as expected. 

Full working example:

```typescript
const input = fs.createReadStream('test.pdf')

const encrypted = await openpgp.encrypt({
    message: await openpgp.createMessage({ binary: input }),
    encryptionKeys: await openpgp.readKey({ armoredKey: publicKey }),
})

```
