### ISSUE TITLE
Signing public key with private key

### ISSUE THREAD

**Issue by larcohex** [openpgpjs/openpgpjs#379] opened 2015-12-03 05:22 UTC
So I tried to sign public key with private key using the code that was provided in Issue #97, but as I understood, it signs using secret subkey instead of an ordinary secret key, so then, when validating a key and its signature, it gives "signing subkey is not cross-certified".

Here is the code for reference:
 ```javascript
function signPublicKey(public_key, private_key) {
  // Returns a new public key which is public_key + signature(public_key)
  var dataToSign = {};
  dataToSign.userid = public_key.users[0].userId;
  dataToSign.key = public_key.primaryKey;

  var signaturePacket = new openpgp.packet.Signature();
  signaturePacket.signatureType = openpgp.enums.signature.cert_generic;
  signaturePacket.publicKeyAlgorithm = 1;
  signaturePacket.hashAlgorithm = 2;
  signaturePacket.keyFlags = [openpgp.enums.keyFlags.certify_keys | openpgp.enums.keyFlags.sign_data];
  signaturePacket.preferredSymmetricAlgorithms = [];
  signaturePacket.preferredSymmetricAlgorithms.push(openpgp.enums.symmetric.aes256);
  signaturePacket.preferredSymmetricAlgorithms.push(openpgp.enums.symmetric.aes192);
  signaturePacket.preferredSymmetricAlgorithms.push(openpgp.enums.symmetric.aes128);
  signaturePacket.preferredSymmetricAlgorithms.push(openpgp.enums.symmetric.cast5);
  signaturePacket.preferredSymmetricAlgorithms.push(openpgp.enums.symmetric.tripledes);
  signaturePacket.preferredHashAlgorithms = [];
  signaturePacket.preferredHashAlgorithms.push(openpgp.enums.hash.sha256);
  signaturePacket.preferredHashAlgorithms.push(openpgp.enums.hash.sha1);
  signaturePacket.preferredHashAlgorithms.push(openpgp.enums.hash.sha512);
  signaturePacket.preferredCompressionAlgorithms = [];
  signaturePacket.preferredCompressionAlgorithms.push(openpgp.enums.compression.zlib);
  signaturePacket.preferredCompressionAlgorithms.push(openpgp.enums.compression.zip);
  signaturePacket.sign(private_key.getEncryptionKeyPacket(), dataToSign);

  var originalPackets = public_key.toPacketlist();
  var packetlist = new openpgp.packet.List();
  for (var i=0; i<originalPackets.length; i++) {
    packetlist.push(originalPackets[i]);
  }
  packetlist.push(public_key.users[0].userId);
  packetlist.push(signaturePacket);
  return new openpgp.key.Key(packetlist);
}
```
Is there any way to properly sign a key?

**Comment by zartdinov** [comment] 2016-02-12 01:19
Hi, I don't belong to this project. But I see the cause of problem. You need to use 
```javascript
private_key.getSigningKeyPacket()
```
instead of
```javascript
private_key.getEncryptionKeyPacket()
```
to get correct key

**Comment by zartdinov** [comment] 2016-02-13 02:27
At first sight I see using  `private_key.getSigningKeyPacket()` instead of `private_key.getEncryptionKeyPacket()`.

Code is mainly from key-pair generation part https://github.com/openpgpjs/openpgpjs/blob/master/src/key.js#L965.

Author provided it such as starting point. There are some errors.

Critical one is that new public key will loose all packets following after primary user packets (rest users and all subkeys packets). And primary user Id packet will be added twice.

Also I think certificate signature packet will contains unnecessary subpackets like preferred algorithms.

Now I thinking about to realize properly this feature with including tests.

**Comment by larcohex** [comment] 2016-02-13 06:41
@zartdinov that would be great, can you update when you'll finish?

**Comment by zartdinov** [comment] 2016-02-13 09:33
@larcohex with ease

**Comment by tanx** [comment] 2016-03-11 04:42
Duplicate of https://github.com/openpgpjs/openpgpjs/issues/97

**Closed by tanx** 2016-03-11 04:42 UTC
