### ISSUE TITLE
Application hangs in IE11 when try to decrypt

### ISSUE THREAD

**Issue by shalenidze** [openpgpjs/openpgpjs#1102] opened 2020-05-25 14:14 UTC
version `4.10.1`

Application hangs infinitely in IE 11 when trying to decrypt the key

`await this.privateKey.decrypt(this.pgpPass);`

In Chrome and FF it works okay.

I'm using compact version
`openpgp/dist/compat/openpgp.min.js`

No errors in console

Is there any solution how to fix it?

Thanks.

**Comment by chesnokovilya** [comment] 2020-05-29 15:38
Could you try older version, for example in https://github.com/openpgpjs/openpgpjs/tree/v4.5.5 internet explorer 11 should work.

**Comment by chesnokovilya** [comment] 2020-05-29 15:40
There is also previous issue https://github.com/openpgpjs/openpgpjs/issues/1084

**Comment by shalenidze** [comment] 2020-06-02 12:09
Hi @chesnokovilya , thanks for the answer, but it still not working in IE 11

**Comment by twiss** [comment] 2020-06-02 16:40
Hey @shalenidze :wave: Could it be that it's just really slow in IE11? It seems to work for me.
One thing you could try to make things faster (but also less secure) is set:
```js
openpgp.config.s2k_iteration_count_byte = 96;
```
_before_ encrypting the key. This will make both encrypting and decrypting the key faster. If you use a strong password / passphrase to compensate for the weaker password hashing, this should be ok.

**Comment by steverecio** [comment] 2020-06-03 15:03
I'm also seeing a regression in IE 11: `Unhandled error in openpgp worker: Syntax error (https://mysite.com/openpgp/compat/openpgp.worker.js:124)`

I just upgraded from v4.4.7

**Comment by twiss** [comment] 2020-06-03 16:02
Hey @steverecio :wave: Hmm. It's indeed bad that it's throwing that error, but please be aware that since v4.5.0, `initWorker()` on IE11 doesn't actually result in the Worker being used, it just silently fails. The reason is that in IE11, Web Crypto is not supported inside Web Workers. See https://github.com/openpgpjs/openpgpjs/issues/993 for more information and potential workarounds. Fixing that fully would be quite a lot of work though, so it might be easier to just not use the Worker on IE11, if that's an option to you.

**Comment by steverecio** [comment] 2020-06-03 17:33
Ok, if that's the case then I will stick to versions prior to v4.5.0. Perhaps the fix should be considered though given that this is broken in the compat version of the library.

**Comment by shalenidze** [comment] 2020-06-04 05:43
Hey @twiss , I'm can't set `openpgp.config.s2k_iteration_count_byte = 96;` cause application is already in production and there are keys already generated with default  s2k_iteration_count_byte, I'm working on migrate from 0.3.2 to latest, so I need to keep encryption working with old keys generated on 0.3.2

**Comment by shalenidze** [comment] 2020-06-04 05:48
also, i have a new problem on v 4.10.1, 
If I generated key in Edge,
I can't start encrypt with that key in other browsers(chrome, FF)
Is there any solution at least for this?, thanks
![Screenshot from 2020-06-04 08-45-50](https://user-images.githubusercontent.com/34502861/83719565-0928ad80-a640-11ea-861d-c0e7b22e7525.png)

**Comment by twiss** [comment] 2020-06-04 09:33
> Hey @twiss , I'm can't set `openpgp.config.s2k_iteration_count_byte = 96;` cause application is already in production and there are keys already generated with default s2k_iteration_count_byte, I'm working on migrate from 0.3.2 to latest, so I need to keep encryption working with old keys generated on 0.3.2

This config option only affects new keys, it doesn't break decrypting old ones. In fact, `96` used to be the default, before we increased it to improve security. Is decrypting those old keys acceptably fast for you in IE11?

> also, i have a new problem on v 4.10.1,
> If I generated key in Edge,
> I can't start encrypt with that key in other browsers(chrome, FF)

Could you try setting `openpgp.config.use_native = false` in Edge before generating the keys and see if that fixes them?

**Comment by shalenidze** [comment] 2020-06-11 08:37
Hi @twiss, 
`openpgp.config.use_native = false`
didn't help, after generation key in Edge I can use it for encryption in Edge but not in Chrome or FF

**Comment by twiss** [comment] 2020-06-11 09:15
Hey :wave: I tried generating a key in Edge, and it worked fine for me in Chrome. What version of Edge are you using? Could you post such a broken key?

**Comment by TikiTDO** [comment] 2020-07-28 16:01
I am getting a similar behavior in node 10. When decrypting the private key with:

`await privateKey.decrypt(keyPassword)`

Sometimes it hard-hangs, other times it resumes after pausing for more than a minute. I will try to do a code read to see if there's anything that stands out.

**Comment by twiss** [comment] 2021-02-27 19:52
Hi :wave: IE11 is no longer supported in v5, so I'll close this issue, apologies. As we continue to try to improve the security of OpenPGP.js, and increase the number of rounds that passwords are hashed, for example, IE11 is simply too slow to keep up.

**Closed by twiss** 2021-02-27 19:52 UTC
