### ISSUE TITLE
Streaming decryption fails on files larger than 2GiB

### ISSUE THREAD

**Issue by ama4tf** [openpgpjs/openpgpjs#1012] opened 2019-12-03 18:01 UTC
Running decrypt on large files fails due to array overrun. This was generated by calling openpgp.decrypt using an encrypted file-stream of 2.1gb in length, a private key, and the binary format. Failure message is below:

Error decrypting message: Invalid typed array length: 2322369312

**Comment by twiss** [comment] 2019-12-13 13:01
Hey :wave: This is a limitation of Chrome / V8; it has a max Uint8Array size of 2GiB. It's possible that you could work around this by using streaming decryption: https://github.com/openpgpjs/openpgpjs/releases/tag/v4.0.0.

**Comment by ama4tf** [comment] 2020-08-27 15:49
We found a workaround by decrypting the larger files in bash but still not a clean fix. I tried switching to streaming both the input encrypted file and output decrypted stream but still yields the same error

**Comment by twiss** [comment] 2020-08-27 16:58
@ama4tf For the streaming solution, please see https://github.com/openpgpjs/openpgpjs/releases/tag/v4.0.0, specifically "Streaming CFB". I think it should be possible to stream files larger than 2GB, although I haven't tried it.

**Comment by ama4tf** [comment] 2020-08-27 18:12
I tried Streaming CFB and that did yield a different kind of error, so still not successful but maybe progress

`RangeError [ERR_INVALID_OPT_VALUE]: The value "3148715314" is invalid for option "size"`

Traceback on the error looks like this

at Object.concat (\node_modules\openpgp\dist\openpgp.js:24175:23)
at Reader.readBytes (\node_modules\openpgp\dist\openpgp.js:24067:51)
at async Reader.peekBytes (\node_modules\openpgp\dist\openpgp.js:24086:17)
at async Object.read (\node_modules\openpgp\dist\openpgp.js:38472:26)
at async \node_modules\openpgp\dist\openpgp.js:38571:22

**Comment by twiss** [comment] 2020-08-27 20:32
OK yeah, this is a bug in our streaming implementation, that we should fix.

**Comment by lekhacman** [comment] 2020-11-03 16:38
Hi @twiss, may i fix this?

**Comment by twiss** [comment] 2020-11-03 16:59
Hey @lekhacman, yes of course, if you want to take a stab at it feel free.

AFAIK, the root cause of this error is this line: https://github.com/openpgpjs/openpgpjs/blob/25118c3f2859c4f5b4c911e7fcd495e20d1cce4f/src/packet/packet.js#L272

There is a long comment above it explaining what it does and why. Under normal circumstances, I don't think this line should be reading 2GB even if the message is larger than 2GB. The first step to fixing this is probably to find out why it does so.

I would recommend working from the v5 branch, and if you do find a fix, sending a PR there. Otherwise this may lead to a lot of rebasing work in the future. Good luck!

**Comment by lekhacman** [comment] 2020-11-03 17:06
@twiss thank you for the hint :)
I let me try to fix this and create a PR.
By the way, i encounter corrupted file after setting `CFB` streaming config. Not sure what happened.

**Comment by fluxquantum** [comment] 2021-03-31 02:04
@lekhacman Did you did you make any strides while working on this? Thank you for your time.

**Comment by lekhacman** [comment] 2021-03-31 02:32
@fluxquantum i'm still reading & trying to understand the structure of the library which is difficult.
meanwhile, I realize that the PGP (or at least this library) is intended to be used to encrypt emails and not large files. But i believe this algorithm is such a masterpiece and should be used for general purposes. So i try to give a hand to fix this.
If you are in hurry, you can use AES (stream reading) as i did. I was trying to encrypt a 20GB file with this library but failed to decrypt so i switched back to AES which solved the problem.

**Comment by fluxquantum** [comment] 2021-03-31 03:29
@lekhacman Really appreciate you for the quick follow up. May I know which library you are using to perform the streaming encryption/decryption? Just to share some more context, in my case there's some more complexity, because I have a java app performing the encryption and javascript for decryption. I am hoping the java solution can be compatible with the javascript approach. Thanks again for the guidance.

**Comment by larabr** [comment] 2022-01-17 13:40
Hi @Bacto ,
> I made some debugging guesses and it seems that this call eats the memory:
> 
> https://github.com/openpgpjs/openpgpjs/blob/6da1c53de7852000fd63bacf1809b7e1ea17cf11/src/message.js#L131
> 

Have you already tried passing `config: { allowUnauthenticatedStream: true }` to `decrypt` ? See documentation about the option [here](https://github.com/openpgpjs/openpgpjs/blob/main/src/config/config.js#L94-L100) .

**Comment by Bacto** [comment] 2022-01-17 14:07
@larabr I did it and... it works!! Thank you so much :)

**Comment by larabr** [comment] 2022-01-19 17:53
Closing assuming this is fixed then, @ama4tf let us know if you still have issues when using the `allowUnauthenticatedStream` config option in the latest version.

**Closed by larabr** 2022-01-19 17:53 UTC
