### ISSUE TITLE
4096-bit key generation only creates 4095-bit keys

### ISSUE THREAD

**Issue by mwlcarter** [openpgpjs/openpgpjs#234] opened 2014-06-11 01:59 UTC
Key generation (at least using Mailvelope) of 4096-bit keys only creates a 4095-bit key.

**Comment by tanx** [comment] 2016-03-11 03:05
Duplicate of https://github.com/openpgpjs/openpgpjs/issues/67

**Closed by tanx** 2016-03-11 03:05 UTC
