### ISSUE TITLE
Keypair generation lenth not correct

### ISSUE THREAD

**Issue by barrydegraaff** [openpgpjs/openpgpjs#227] opened 2014-05-19 09:50 UTC
When I do this:
var key = openpgp.generateKeyPair({numBits: 1024, userId: userid, passphrase: passphrase});

Using version 0.6.0.

The resulting key is:
gpg --list-secret-keys FA2BCAEF
sec   1023R/FA2BCAEF 2014-05-19
uid                  hgfj
ssb   1024R/AB3B66D8 2014-05-19

I would expect sec to be 1024R, as far as I can see this is not a big issue, but it looks like a bug.

**Comment by tanx** [comment] 2016-03-11 03:08
duplicate of https://github.com/openpgpjs/openpgpjs/issues/67

**Closed by tanx** 2016-03-11 03:08 UTC
