### ISSUE TITLE
Error: Error decrypting message: Session key decryption failed

### ISSUE THREAD

**Issue by sylarwang** [openpgpjs/openpgpjs#1351] opened 2021-06-25 21:36 UTC
our client use the public key we generated from this tool and encrypted the message, but with this tool we can't decrypt it, it reported `Session key decryption failed` error, I have created a test case as below, you should be able to reproduce it:
```
it.only('test decrypt private key',async function() {
      let pk = [
        '-----BEGIN PGP PRIVATE KEY BLOCK-----',
'',
'xcaGBGDWSgMBEACvqXr7BXAGepCdBDTo32zNFi3vcaDxDivaTs9SOajqvxM0',
'T3+nrWgpUq9PdKnYLDxa6E6JrMyDMPMBVWGfM3jOuw1v1i+BnArJ7OzKDvu4',
'oqAlEgNjgoxOeC5tcveA/4EV2s0/iL8YIotpxh+pMscT9Oma3Nn0otC482Nq',
'Zp2m+i1hpQ6LWaGPW8UreQDPKwGzCGjpKFTtga4cbygbuVZ8daW+y0ZwywBc',
'prNn3aOtDQ5s9g4vq9KYnWaAhddCFlE20ipPTrN/ihJyfrkX1pxEPL9obOoC',
'sP7Uai7traUqf8GNxESaWOp4Pf6x4leQev63wqydxC2pyV5JJkIHvMngk5CD',
'sqC/b6fuHPKAbLV+UvbXFEIgAnEkAMqU/ODOni0mXKcA48H9AfZVwR9OOLrs',
'vZNQImwmXpZr0ZUfcuijoshuXbO9dU2Ch3Ex7pmvVOc0bf2icdhmLEAtz2Pq',
'sSkxZ0A/6g0++g7Ug6wS6j2lpW7mCfmrz8A1eAKSB6RlthYVAIuz9t7JfIvl',
'yN9/G2nThwC37m6ibyn3XpJgbzBSPZdSgibUnh4c+ZMbTux2SRZ5GxAmJ3vS',
'W4iDeaxXNOl0LSDyg+kA6JUxB/QPLm4Fre+pksYJHNRkGWTi51+Y+kXcOd5P',
'6bmjK/6bDxdMYztw8B/DyirhFNdjTuBTq2uJHwARAQAB/gkDCKzQPIHS6dzs',
'4GLtcuufen9afVU3kEUtFj5QUslbn3nOR/5MwwwZdV/QV3BDcZB07cE8ISCg',
'Bc+UCn1hm2wqAVkd+WGap/F9gr293/+8YnEp/4ev20ssQn65N7HDkCTdAA10',
'ModCr+EBZ/u697DGbgSgOmhymWv8GoD8k3krAKa+ogxSZjPy+8IPOVF3TtqZ',
'/p0FP0cac+/lJDsGQUDajN16U0uftZKGi6qKsSO/0fyzRH7UlqF3DS/wCT3O',
'WMu84KwfXL/kghbsAzRr4elK10AGdHISklBfB28bVjCL6ZN55Rn/82aj6H/1',
'iliJfxFZsKCSuqGO60XwK13D52Ac6HAYNQZsUCN/XRkS5OlWJ6VCwvdhB7q2',
'eDqYgE/1n+oydNIEmTbSYUpAnKe3ttOFz5/rnyMjcapiaA+Yl4WA+qQCybr/',
'+s1GleM8YH3ivVlAW5zmsFBPovWaUhBQCP9jBhfH3xYfHRlCKNfRWv/25Ptm',
'/DoI7BfpqI/zov4+WUTmj9thbKtu28EKKPbv/OKEIPOs2WB40mzyAaaKhnv0',
'iLMC9kUX+jh/R/Nwv4txvtMzLUyt+qk0k66Lko/4b5IyfKRbIw/GCMA0TNEf',
'1bdL49AG45NDp7cDVuOkMrU4JaLEXlLN4q0flNUujYHIPqghVuDJTpwZh+xk',
'DSdzzaAJJSEbkwyvDkxASSF0CeDWqbbvA6rb19om//y/eUWnOlrffaSRGgpP',
'6R+hXl/vgVn8CfwsFvPaEF+hZ4MmBclfTc3piuz8PepSwVI+bSHR9XrSD2ca',
'wJ116RNJOHh1TQOFZTFsSxOBh23F3O/rqElV0BesaTHsWCW6kyhBct23gXtv',
'uAPJActRUMt0+z1Bk6qJylrz6ZRXwvLnIC9ZiEYkFSHAnccmXNLYyfNFnqbH',
'XPYbyneM5rnoM7psRFK+jZbjmtXuU5tDtzvHP4Of92u443d3YS1PrHQdK4ki',
'4ZEKgHSVHWQiwEr43cMBWwxwepo9tknMuuiUr94c1FkHj/IBXKCobmhjlXJN',
'8p8BD3wwJvZ4i82KHX2OikeMvIDq57fCH8NwO7iN5sn/Qlg3tyZBFbiBRysf',
'ehEcNKm4tmFN5zZIjS+d59Z92uPtIVt7Fj9qRMswNpEEToUU0XiQ2Q0tBEtN',
'Y9qb6BMNypnlvkGx7yMuO0xHqXvfJHmyHf06V4KtOJwS09giBKI6TjT7QDLm',
'KRX9OuFAnjQsBLLobhrzkSEPDcvvxJdJgRXwodr8lxmDfSS8a/JrL+2sRBGa',
'p/X0Onog99VkFBsPJyxngVTK0vrqEjUVOOvkRO7ZOEgEs0ztjEqF+eTd5b6W',
'MFtM3hIPrShYcSAwfe0cR1f/jkn+lGJO9OUb4/dZC897ydyTAzCCzyKvlsHm',
'vrLXYbOsoo9w0nIbwtHgTo1HbV7x20HMaASoqHEo80/dn4IQGMSQaumszr46',
'JqPYYK7JMMUeh6oalaOiYLtkZ0H+8D2lpY9oitfDnkd5Il9hnY/e0ebnb0vS',
'RB1u5N70/pEsyFfCueiIuKeuTrPnit0RNhOiitHK/1j6qKhvl65U3TcXmdBE',
'd/ka2SPnDT9n7zfzBrabDXB45/yDz+vskLWxnVjlTQ+A0SnH9lJk/oP71oYq',
'zY0W1LglyT1HPgD0uas3tRgXzYZqtDZQbVDnWi6ID6GWOVC/qW6E3V3mQeO1',
'qN8XIKf7EOzqck9LS0dj71n1jXVCa3Uz1tIx+dkC1uPY+RAm8M80l4zinEY4',
'bNJI11oF0pu14S3hjYbUkTbbL8PNLWZ0cC13YXRjaGVyLWFkbWluIDxmdHAt',
'd2F0Y2hlci1hZG1pbkBpYm0uY29tPsLBigQQAQgAHQUCYNZKAwQLCQcIAxUI',
'CgQWAAIBAhkBAhsDAh4BACEJEFdm0eoLFAhWFiEEXviRn6SEhyS73aJHV2bR',
'6gsUCFZRwRAAnsxxJuNL/e7cpD5Ix/w3ur9ukAo7tG/LOckrl5uvgcweUfN/',
'OBQcWQdxG+A/Qpnt05/nkr+5ta4dHorLTIYyOnSz8+J/KcTNXsAUV4BU3DUo',
'uYRHKcD9CMBufUloO+BkEraP4t/rMkSi1YHSwDctuM1kNGLHgf1J9ln/PFMc',
'+M5S2tbOuXtQm5B3kcv7c5Wc5mFwUPIexxhXLyqHTSsdvXZF05aRAjot1jaZ',
'vC7jEx+aC0CfVhXF5PE0brlJQobb3Wytmi4FS9xA7lZu+5Q3//sAph+CZeSJ',
'Ta/3lEmUq6IHueu18TWIOuHuBGSyvzzsGuQ9lovJI5bJnq/0CuyPpxSJVGot',
'Eh4dS/jJUCgEKT/y8ke3Ynn15mkMVd5Sc30Bkg2mnhNUTyHQ/4orqRWBHKL7',
'KmMa95iOo0joD2V11HxTS9eVm9Gpotbla2samSfNayeRfuGzyqT9bcj+muOq',
'jr12/REybD7/D4Pq32FsPMDaS+xJvf3DjCsFlFvgQQy4YWpqOgQdSpGLrFqm',
'jFsTQqD+eJVU3DokeXq75pxNgtTtIU0dPUctRiLCY/z1c5H1dh3APcvJIfkV',
'DBBCKCNdd8ArIb9/COMdbmV088ADvdeT3dYLWQwAUIwyzuRHdIoTph2d3+f9',
'u/IC9ZE4AQfxUxC07mK9wCfiUmP49PhttF3HxoYEYNZKAwEQALNg9F/zWa0V',
'hWRLtUwwtp+wXsaNAi6osVVY4xoBvu0UktQZEQ9h3Hdhvfyq/IrsviZ3Lm71',
'5XxfMDScIagCXWLBZ/IeoFVwo7A/ILW8ozBWvbdTI6ndW/CrZFmTr7+jbCjV',
'vG0dCFOk7NX7lj586bTTK39XRrJQa94GPBPvtbyO83msdWm849Q4sBPU/lbE',
'18WFUpOkdFbg8DrWDk087boKN6AnrNlQIn9IigUG7H9Znj7NRu0WnmxQjbBy',
'u6BXthC2WwhBpR3XT5PWAmbDlu+bN+wUg+BrCTUK5xTHMIEfT3Jay3PZTEyJ',
'v6Zg0xa0h6LnadYcyBdQYCH/A3ntxDOx7HN5CyRyIQNP7nDvVEL5Q316oagD',
'EDYg6TzqSrmTjnFCLTOVG0ScsbaO2TcIq8hUdUu0xeW2Xq9uC7rM94FZHqWH',
'O3ArxK7dp1f3g4x0OG5XJac6hxqE46VyBHIWxNkwK8gBLp/TC3Ilu6b26QYx',
'WnRC/f00XHEJ9Kt9ftnVbDSu/Tdr8kEmroQVWF1wx2VfsUZdHwhN2C6zMD8R',
'9MGWsy/louUdvxml41/JbhRYgCmGsYZGI7XLERLCgevMvwZidv5rBELF7wKT',
'nFnzjz3M7WMQ7kShup1w6uMqEiU+OTPsHtC+Cl4Ew95+XUEGH6WecYqmM6gM',
'DmehoXcJn8HjABEBAAH+CQMIJ6RdQMzgEWPgmkJQsnwG7StxfatIbozAGWiK',
'OminCRxUOICnBlAoxZ6Dhx3SUUbwkFwOBnP+gq8Gina/zEQY+xBeqDkc1b8U',
'qM3g337i809ACblxa0iSorAvXZN+mZPl4WQcWu6bf1csKv0SD3CT9LaKpx2a',
'nlw26zMMldEnhdhCaH1SI3b8g0xdRMkdkNwMsK9S7DrHgdhm/8HLLJMnUEAs',
'+pc2H6xFFKtUBeKo+WHFta3TbJm3bB3Zs5YM9SlJfBZfwEGHaLEq7m/eEKKA',
'WD8i84nC9DQ6wy3iXp9MmRGlNKnNXfq5X/sr3e4j5nBJnrcJ4DwAEqsZRarO',
'wB/8Ersx8R8kMms/wFDMSadAhRXTVWQ2En+03pDoYineZ7QWonDEzoWfPbv4',
'D2dYfnonxqXKYLiJjcOmNHdunapXIh80AdLjKRgYKx0lSW+YqQ7sM9MtiB4o',
'6FzNn8Habn1w5c10M6iDIMPARh5vj/dLWDGxwFUzmvhFC0iDxbIBx3TV14xT',
'E5LlX7S5GXkwFTzbqNHbKHqs+5ny/0xHaoY+0JMJb6zniSZcPVY2uLgOT3ks',
'W+WH060uQpacuVZiZ4+XzXWMBL5hc4ZVW9yYeXnaZ63M7dWPVseoIKMRc6X9',
'KXF02BYHyA1HODXk+gTPkOja6f2uTJJevVVKQiOnbzzoylsscrbYxIkTj5jm',
'zNajwuobhdg0KEGdTInG/GWLEoQbbi7kUTE1Yb5IGtD9Abpm86mxDEsczeyM',
'LTEWhVT8vIhArUMiGaAAjq+Lc1p+mdFB2oWORygTAYAdX/pFqLIc8deyfd0k',
'3rkX4XAodXskQxQSXshX9MVuewzO1OWOGAjo4iX5M2a4MFz7i1YT65YAzDLF',
'NWJkjv97SFr6V3Y4HG2iv6K/Qzc0PUx2Om/HYQkPuJt2R98cB37NDnf56B8J',
'ijVQNij8rnWZBS3jLOgiTQ9chpf4DwHQaMd9eFUbWIlZRXkc3vuR0ijykaQp',
'GKknzayQU3cB5HS82JrmTOW44yI5Akl0fkTIOWwEG4fXxpLd2RBoketBHEP7',
'YPl1ez19jiWqxhcA7c97MHLfzyc/93mfu7Vyq1KUNTfqmwgq8b4Hrh2kieGw',
'f2njC9nSSJAaQ+bTfAu8Zu5oNCWjfFMw3aHm6MwC5xK7Y/LV1aPSvc8Ja1+M',
'nOPLmcWVnRXFuogQx7ZOp6ugDR3i/+t8h6ZbZPM0C4PSN2JoxE2DOHLIEUua',
'oLt2lwZzzeQQwynK0g2PUKbOiRBVu1/kHTOU3xiqkTW8O38W5VyThtQ1U2+H',
'QRdcmXuZ9GXg86+IKrDiprnjah8H3EaO5QO7/47Vxs8ForGsGnAL8erAwfdt',
'PdHrgFp0wKP3u4v2JIR6KS0ALcXzakPK3g/h+D+Tzy8Hey86+b4QW7qYVXao',
'PIkbIdMrywtqUzgh5GKqzrrCztFquG3Q1RQzbUgUs0sTUVNEXbu4+YGo+iuI',
'ETOeSxIjIBLHK1duWUuamzhFDyeO71wbyyzNETxBvB/QihcRWnTL8OgEhFiu',
'DrrrqjrYEt/yKz+FUFip3YnY/8LzahyCV7wIJZ4T8A5uMgJj418uuARuCGbu',
'3xOBdyuqgIKAF5YaynyTOc3DKS0qiab3JAvPXfDpt51TIHOzemsYrV0GvZVG',
'YG+rw/mqG6cTTwbd9WqqqCltSh1xX5lhKF4F9jbmtPOSt3olkAi8Li9QvXJD',
'OLttJwctiNswrnDwmRFvGuZ+u2QlEEsk7wIGXxgSKasp8/JeB0Xox9Cj15Cs',
'HMLBdgQYAQgACQUCYNZKAwIbDAAhCRBXZtHqCxQIVhYhBF74kZ+khIcku92i',
'R1dm0eoLFAhWyXgQAJ/VMKTaLufzkVccYMNcPvBo0MwS2GUzKLNRn1v3e+iN',
'tBgljFHNIi/WfVz1+BAAYy7aUNZ1RnuR9fFWkLE5vS2FR+bXxiZ25GTTLVdK',
'9qt0BEI0JkikBiPaOk6kgwRnN36pVPCLBgHRVPvufG87Y0tt/iP80DgDz5db',
'QB8U0DCPIpjyp/qN/3zy5DEFSABFKuLRG6qOqF4W2ErZTNinnIsQmwk5k5+u',
'ii33a890WofM35NauDk3A/U0VN87LDxgnmdw1/XIPzM+dvGNEfitHv7zkVUz',
'h7ii+cihCO3Wl72IMSxgQKFgYk9mXkR5te3O9flC5TQQTsf7JA7JvDMBp8Mk',
'/ly0rT2ZvNN7ERWKzTaeATLOEPv0OELjf3Z9BYk65/IQS5x2vSXQOa7OOZ0Z',
'vsarW90UhbIwVqUivvkMXCjkzIFVBd77ITV4rekcJh6DQ06fgdtNbBApKHXx',
'm9Mm8m+ekQPvN9VziwvXuqqo8vesYL4weI9z644u+AZ8C/+VOeLq/XiQVgub',
'8yqdG1YBvs9icEar2DdctSA6IOL9x3r3JGCNnpKOTTXWBsKihviFuoDM6BPS',
'z1Ii8oDgPiIqMnIQCtzZXIO9JyoXvc7gO0bxTthLCOFU3hmXt5GQHIRyHwo2',
'z701EZ4gOcxqOLEHz4GrO+uNbuawvkpjtgl5yfec',
'=J6Ng',
'-----END PGP PRIVATE KEY BLOCK-----'
 ].join('\n');
      const encryptedKey = await openpgp.readKey({ armoredKey: pk });
      const privateKey = await openpgp.decryptKey({
        privateKey: encryptedKey,
        passphrase: "superSecure"
      });
      const decOpt = {
        decryptionKeys: privateKey
      };
      const encrypted = [
        '-----BEGIN PGP MESSAGE-----',
        'Version: BCPG v1.63',
        '',
        'hQIMA1dm0eoLFAhWAQ//WXF/s/Aj6fxz0hV83R50hhFnMnTxPNKLqBAC3dYBSduj',
        'mJAA4N5CJztO8HTzqu4MreQdk5OldpVr0ahUUBhnDnkAO/zkNqUEvU76ECEqa+T1',
        'ZcukkfzzAG9FD3chLIhZDpVJ79zfxb2OUQ0+C0TeO3i1M0ubJrXEwYzFTU/u7nfG',
        'xcS/jh6IrGUfNUIgwRaru7sQaaNkQO4VSV6M+ppUz6cw4jXeDi6rBTSCoyJ5HA90',
        'm9RWuKTx1xtNbwYGtUJYK2z2ua/NUtfS4MPoJmevEyCW23BJaES7UMCAqFwzVsQi',
        't3f7y3H6hFXzdFYkUTlG/Bq0U5Ym+gcT0pf3QPaklyfYPAqBDsQpiv0XUG3l0gy/',
        'LtaKjjwZxqi7lMjn49w7Lh7tPWnTBewtriSn3ivqYBqKVzHwac0vHi80qqgGKZ8G',
        '9e1N7lzhqpPI28UfMX0ZEtJiY3CBK+81tDwTrTo0XzRQ9XXG04NVqa2/erXGLY/N',
        'J6Zk+Y+RXRxao1FRgjoiD40Ch2O4VO8AeNW5IKNx140ZlDn6J79tXosuLwM25mfb',
        'PK/NEYlp4NH3PR3wd/Pc7cDhe3oQeniUCn1As1xMpmYuZcDxYvyBF9f4P7xzS50s',
        'ozrSIfFxaK8++PNTXB/hJ7SZrp0hp4VpOaXC1jFTPtlXq7LiYJqtD92yzNjnHhDS',
        'PQEyNtPjJnfXqIE7oD7Kxn6Z1/79Wz7P+rujoQ9i39nMb6Q9NSr23lp58ccvxlVE',
        'wPtEXoy+eVE3oOw6YZw=',
        '=EzwZ',
        '-----END PGP MESSAGE-----'
      ].join("\n");
      decOpt.message = await openpgp.readMessage({ armoredMessage: encrypted });
      let decrpted = await openpgp.decrypt(decOpt);
      decrpted.should.be.equals("hello hello");
    });
```

**Comment by larabr** [comment] 2021-06-28 08:37
Hi, the message was encrypted with the primary key, which is marked as sign-only. The encryption library shouldn't have used that key to encrypt. To allow message decryption, you can set `config.allowInsecureDecryptionWithSigningKeys` in the decryption options like so:

```js
const decOpt = {
  decryptionKeys: privateKey,
  message: ...,
  config: { allowInsecureDecryptionWithSigningKeys: true }
};
```

That configuration option was introduced to go around a very old OpenPGP.js bug (#1148).
You might want to open a BCPG issue, if they haven't fixed this behaviour already, since the problem is on their end.

**Closed** 2021-06-28 08:37 UTC
